FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
COPY . .
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common 
RUN pip install --upgrade pip 
# RUN pip install wheel setuptools pip --upgrade

RUN pip install -r requirements.txt


EXPOSE 8505
ENTRYPOINT ["streamlit","run","streamlitapp.py" ,"--server.port=8505", "--server.address=0.0.0.0"]